### PR TITLE
Feature/design

### PR DESCRIPTION
**Pull request by epinczinger**
This branch is built following the next features:

Set up of Javascript using Webpack.
Use of NPM.
Modularized code.
Use of Loaders and Plugins.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @epinczinger 
### You have done well so far :clap: However, there a few issues to be fixed:-
- [x] Remove unwanted files like .vscode
- [x] Add more scripts in the package.json. Install all the required dependencies and configure them properly. See below
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" 
  },
```
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by epinczinger** [comment]
Hi @rOluochKe!
The suggested changes have been done, however, I had to modify the script "start" so it works for Linux Mint (my environment).

Thanks for the review.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Comment by epinczinger** [comment]
Thanks, @mikenath223 !!

**Pull request merged**
